name: "test"
description: 'test'
inputs:
  test_input:
    required: false
    description: just a test
runs:
  using: "composite"
  steps:
    - name: echo flutter version
      shell: bash
      run: flutter --version
    
    - name: echo lcov
      shell: bash
      run: lcov -v