name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: echo secret.GITHUB_TOKEN

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      
      - name: get file changes
        run: | 
          git fetch origin ${{ steps.comment-branch.outputs.base_ref }}
          changedFiles=$(git diff --name-only origin/${{ steps.comment-branch.outputs.head_ref }} origin/${{ steps.comment-branch.outputs.base_ref }})
          for file in $changedFiles; do
            changedModule=$(grep -oh "\w*_module\w*" $file)
            echo $changedModule
          done

          echo "::set-output name=changedFiles::$changedFiles"
        id: get-app-changes
        
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
      
      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      # - name: Testing app
      #   working-directory: ./app
      #   run: |
      #     flutter test --coverage
      #     genhtml coverage/lcov.info -o app/coverage

      # - name: Generate coverage
      #   working-directory: app
      #   run: |
      #     percentageRate=$(lcov --summary ./coverage/lcov.info | grep "lines......")
      #     echo "::set-output name=percentageRate::$percentageRate"
      #   id: get-app-percentage
      
      # - name: Analyze
      #   working-directory: ./app2
      #   run: flutter analyze

      # - name: Testing app2
      #   working-directory: ./app2
      #   run: |
      #     flutter test --coverage
      #     genhtml coverage/lcov.info -o app2/coverage
      #   # lcov --extract coverage/lcov.info 'lib/src/pages/*/*_view_model_impl.dart' -o coverage/lcov.info

      # - name: Generate coverage
      #   working-directory: app
      #   run: |
      #     percentageRate=$(lcov --summary ./coverage/lcov.info | grep "lines......")
      #     echo "::set-output name=percentageRate::$percentageRate"
      #   id: get-app2-percentage

      - name: get PR number
        uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: get-PR-number
        with:
          github-token: ${{ github.token }}
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          filterOutClosed: true
          filterOutDraft: true
      
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.get-PR-number.outputs.number }}
          body: | 
            Job Summary
            
            ```
            changes: ${{steps.get-app-changes.outputs.changedFiles}}
            ```
            
            for further detail you can check this action summary
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
            name: coverage-details
            path: ./*/coverage
