name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: pwd

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
      
      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      - name: get PR number
        uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: get-PR-number
        with:
          github-token: ${{ github.token }}
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          filterOutClosed: true
          filterOutDraft: true
            
      - name: get file changes
        run: |
          git fetch origin ${{ steps.comment-branch.outputs.base_ref }}
          changedFiles=$(git diff --name-only origin/${{ steps.comment-branch.outputs.head_ref }} origin/${{ steps.comment-branch.outputs.base_ref }} | grep -oh "\w*_module\w*" | uniq)
          for file in $changedFiles 
          do
            finalString_$file=$file
            echo "finalString_$file=$finalString_$file" >> $GITHUB_OUTPUT
          done
        id: get-app-changes

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.get-PR-number.outputs.number }}
          body: | 
            Job Summary
            
            ```
            ${{steps.get-app-changes.outputs.finalString}}
            ```
            
            for further detail you can check this action summary
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
            name: coverage-details
            path: ./*/coverage
