name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: echo secret.GITHUB_TOKEN

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
      
      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      - name: Testing
        working-directory: ./app
        run: flutter test --coverage --no-pub --coverage-path=./coverage/lcov.info

      - name: Generate coverage
        working-directory: app
        run: |
          genhtml coverage/lcov.info -o coverage/html > coverage/temp.txt
          sed -n '/Overall/,$p' coverage/temp.txt > coverage/coverage.txt
          rm coverage/temp.txt
        id: coverage-generator

      - name: get event data value
        run: echo ${{ github.event.issue.pull_request }}

      - name: generate summary
        working-directory: ./app
        run: |
          lcov --list coverage/lcov.info > coverage/summary.txt
        id: coverage-summary-generator

      - name: Get comment body
        working-directory: app
        run: |
          body="$(cat coverage/coverage.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
        id: get-comment-body

      - run: env

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.comment-branch }}
          body: |
            ${{ steps.get-comment-body.outputs.body }}
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}