name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: echo secret.GITHUB_TOKEN

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install node dependencies
        working-directory: ./.github/actions/github-actions-report-lcov
        run: npm install

      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      - name: Testing
        working-directory: ./app
        run: flutter test --coverage --no-pub --coverage-path=./coverage/lcov.info

      - uses: actions/checkout@main

      - name: Report Code Coverage for Testing Discovery Module
        uses: ./.github/actions/github-actions-report-lcov
        with:
          coverage-files: ./app/coverage/lcov.info
          minimum-coverage: 50
          artifact-name: code-coverage-report-discovery-module
          working-directory: ./app
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Post jest coverage comments
      #   env:
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #     REPO: ${{ github.repository }}
      #     SUMMARY_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #   run: |
      #     coverageSummary=$(lcov --summary ./app/coverage/lcov.info)
      #     curl \
      #       -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #       https://api.github.com/repos/${{ github.repository }}/issues/ ${{ github.event.pull_request.number }}/comments \
      #       -d '{"body":"# Job Summary\n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n'$UNITTESTCOVERAGE'\n"}'

      # - name: get data from summary
      #   run: echo $coverageSummary