name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: echo secret.GITHUB_TOKEN

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
      
      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      - name: Testing app
        working-directory: ./app
        run: flutter test --coverage --no-pub
      
      # - name: Testing app2
      #   working-directory: ./app2
      #   run: flutter test --coverage --no-pub
          
      - name: get PR number
        uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: get-PR-number
        with:
          github-token: ${{ github.token }}
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          filterOutClosed: true
          filterOutDraft: true

      - name: Generate coverage
        working-directory: app
        run: |
          genhtml coverage/lcov.info -o coverage/html > coverage/temp.txt
          sed -n '/Overall/,$p' coverage/temp.txt > coverage/coverage.txt
          "" >> coverage/coverage.txt
          rm coverage/temp.txt
        id: coverage-generator

      - name: generate summary
        working-directory: ./app
        run: |
          lcov --list coverage/lcov.info >> coverage/temp.txt
          sed -n '/    /,$p' coverage/temp.txt | tr -d '%#%' >> coverage/coverage.txt
          rm coverage/temp.txt
        id: coverage-summary-generator

      - name: cat coverage
        working-directory: app
        run: cat coverage/coverage.txt

      - name: Get comment body
        working-directory: app
        run: |
          body="$(cat coverage/coverage.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
        id: get-comment-body

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.get-PR-number.outputs.number }}
          body: |
            Job Summary

            ${{ steps.get-comment-body.outputs.body }}

            for further detail you can check this action summary
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
            name: coverage-details
            path: ./app/coverage
