name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    outputs:
      head_ref: ${{ steps.comment-branch.outputs.head_ref}}
      base_ref: ${{ steps.comment-branch.outputs.base_ref}}
      flutter_path: ${{ steps.get-flutter.outputs.CACHE_PATH }}
      flutter_key: ${{ steps.get-flutter.outputs.CACHE_KEY }}
      get-matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: define matrix
        id: get-matrix
        run: |
          if [[ ${{ startsWith(steps.comment-branch.outputs.base-ref, 'main/') }} = true ]]; then
            echo "matrix=['dev','staging','production']" >> $GITHUB_OUTPUT
          else
            echo "matrix=['dev']" >> $GITHUB_OUTPUT
          fi

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ${{ fromJson(needs.setup.outputs.get-matrix) }}
    steps:
      - name: trim string flavor
        id: get-trimmed-flavor
        run: |
          echo flavor=$(echo ${{ matrix.flavor }} | sed "s/'//g") >> $GITHUB_OUTPUT
      
      - name: echo current running matrix
        run: |
          echo ${{ matrix.flavor }}
          echo ${{ steps.get-trimmed-flavor.outputs.flavor }}
