name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      # - uses: xt0rted/pull-request-comment-branch@v1
      #   id: comment-branch

      # - uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "2.10.5"

      - name: Get Pub
        working-directory: ./flutter_application_1
        run: flutter packages pub get

      # - name: Analyze
      #   working-directory: ./flutter_application_1
      #   run: flutter analyze
        
      # - name: Testing Authentication Module
      #   working-directory: ./flutter_application_1
      #   run: flutter test --coverage

      # - name: Report Code Coverage for Testing Discovery Module
      #   uses: zgosalvez/github-actions-report-lcov@v1
      #   with:
      #     coverage-files: coverage/lcov.*.info
      #     minimum-coverage: 50
      #     artifact-name: code-coverage-report-discovery-module
      #     working-directory: ./flutter_application_1
