name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: pwd

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          cache: true
      
      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: define matrix
        run: |
          if ["$()"]; then
            echo "matrix=[dev,staging,production]" >> $GITHUB_OUTPUT
          else
            echo "matrix=[dev,staging]" >> $GITHUB_OUTPUT
          fi
      
      - name: trial composite
        uses: ./.github/actions/test-composite

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [dev,staging,production]
    steps:
    - name: echo current running matrix
      run: echo ${{ matrix.test }}

    - name: check flutter version
      run: flutter --version
    
    - name: check lcov version
      run: lcov -v
