name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    steps:
      - name: echo github credentials
        run: echo secret.GITHUB_TOKEN

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
      
      - name: Analyze
        working-directory: ./app
        run: flutter analyze

      - name: Testing
        working-directory: ./app
        run: flutter test --coverage --no-pub --coverage-path=./coverage/lcov.info

      - name: Report Code Coverage for Testing Discovery Module
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./app/coverage/lcov.info
          minimum-coverage: 50
          artifact-name: code-coverage-report-discovery-module
          working-directory: ./app

      - name: get summary coverage
        run: |
          lcov --summary ./app/coverage/lcov.info >> $GITHUB_STEP_SUMMARY
          echo "COVERAGE_SUMMARY=$(cat $GITHUB_STEP_SUMMARY | tr '\n' '===')" >> $GITHUB_ENV

      - name: get summary report
        run: |
          echo "${{ env.COVERAGE_SUMMARY }}"
      
      - run: env
      
      - name: Post jest coverage comments
        env:
          PR_NUMBER: ${{ github.event.issue.pull_request.number }}
          REPO: ${{ github.repository }}
          SUMMARY_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d '{"body":"# Job Summary\n'$SUMMARY_URL'\n'$UNITTESTCOVERAGE'\n"}'
