name: Testing-CI

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:

      - name: get file changes
        run: |
          git fetch origin ${{ steps.comment-branch.outputs.base_ref }}
          changedFiles=$(git diff --name-only origin/${{ steps.comment-branch.outputs.head_ref }} origin/${{ steps.comment-branch.outputs.base_ref }} | grep -oh "\w*_module\w*" | uniq)
          for file in $changedFiles 
          do
            finalString="$file : $file % blabla of blabla"
            echo "::set-output name=$file::$finalString"
            echo "result_$file=$finalString" >> GITHUB_OUTPUT
          done
        id: get-app-testing

