name: CI

on:
  issue_comment:
    types:
      - created

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && (github.event.comment.body == 'build' || github.event.comment.body == 'deploy')) }}
    outputs:
      head_ref: ${{ steps.comment-branch.outputs.head_ref}}
      base_ref: ${{ steps.comment-branch.outputs.base_ref}}
      flutter_path: ${{ steps.get-flutter.outputs.CACHE_PATH }}
      flutter_key: ${{ steps.get-flutter.outputs.CACHE_KEY }}
      get-matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: define matrix
        id: get-matrix
        run: |
          if [[ ${{ startsWith(steps.comment-branch.outputs.base-ref, 'main/') }} = true ]]; then
            echo "matrix=['dev','staging','production']" >> $GITHUB_OUTPUT
          else
            echo "matrix=['dev']" >> $GITHUB_OUTPUT
          fi

  test1:
    needs: [setup]
    runs-on: ubuntu-latest
    outputs: 
      flavor: ${{ matrix.flavor }}
      get-matrix: ${{ steps.get-matrix.outputs.matrix }}

    strategy:
      matrix:
        flavor: ${{ fromJson(needs.setup.outputs.get-matrix) }}
    steps:
      # - name: trim string flavor
      #   id: get-trimmed-flavor
      #   run: |
      #     echo flavor=$(echo ${{ matrix.flavor }} | sed "s/'//g") >> $GITHUB_OUTPUT
      
      - name: echo current running matrix
        run: |
          echo ini adalah flavor test 1 --${{ matrix.flavor }}
      
      - name: define matrix
        id: get-matrix
        run: |
          if [[ ${{ startsWith(steps.comment-branch.outputs.base-ref, 'main/') }} = true ]]; then
            echo "matrix=['asd','qwe']" >> $GITHUB_OUTPUT
          else
            echo "matrix=['asd']" >> $GITHUB_OUTPUT
          fi
  
  test2:
    needs: [setup, test1]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ${{ fromJson(needs.test1.outputs.get-matrix) }}
    steps:
      - name: echo current running matrix ${{ matrix.flavor }} --${{ needs.test1.outputs.flavor }} ${{ jobs.setup.outputs.base_ref }} 
        run: |
          echo ini adalah flavor test2 --${{ needs.test1.outputs.flavor }}
